name: vector_tile_query
version: 0.0.1
description: >-
  A Dart package to query reverse geocoding on vector tile protobuf files (mvt/pbf).
homepage: https://github.com/saigontek/dart-vector-tile-query
documentation: https://github.com/saigontek/dart-vector-tile-query
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  vector_tile: ^0.1.4
  meta: ^1.2.4